-- ====================================================
-- 简历星球 (Resume Optimizer) - Supabase 数据库初始化
-- 使用方法：在 Supabase SQL Editor 中粘贴并运行
-- https://supabase.com/dashboard/project/jbdaabtcektgxtblwoow/sql/new
-- ====================================================

-- 1. 用户表
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    nickname VARCHAR(50),
    avatar TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

-- 2. 简历记录表
CREATE TABLE IF NOT EXISTS resume_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT NOT NULL,
    extracted_text TEXT,
    sections_json TEXT,
    suggestions_json TEXT,
    images_json TEXT,
    user_id BIGINT REFERENCES users (id),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_resume_records_created_at ON resume_records (created_at);
CREATE INDEX IF NOT EXISTS idx_resume_records_user_id ON resume_records (user_id);

-- 3. 简历版本表
CREATE TABLE IF NOT EXISTS resume_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL REFERENCES resume_records (id) ON DELETE CASCADE,
    version_name TEXT NOT NULL,
    style_type VARCHAR(50) DEFAULT 'standard' NOT NULL,
    sections_json TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_resume_versions_resume_id ON resume_versions (resume_id);

-- 4. 经历问答表
CREATE TABLE IF NOT EXISTS experience_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    question_key TEXT NOT NULL,
    answer_text TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    CONSTRAINT uq_experience_session_question UNIQUE (session_id, question_key)
);

-- 5. ATS 检测报告表
CREATE TABLE IF NOT EXISTS ats_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL REFERENCES resume_records (id) ON DELETE CASCADE,
    score INTEGER,
    issues_json TEXT,
    suggestions_json TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ats_reports_resume_id ON ats_reports (resume_id);

-- ====================================================
-- 触发器：自动更新 updated_at
-- ====================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_users_updated_at') THEN
        CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_resume_records_updated_at') THEN
        CREATE TRIGGER update_resume_records_updated_at BEFORE UPDATE ON resume_records
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;

-- ====================================================
-- RLS (Row Level Security) 策略
-- 每个用户只能看到自己的数据
-- ====================================================
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE resume_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE resume_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE experience_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE ats_reports ENABLE ROW LEVEL SECURITY;

-- 公开策略（允许 anon 和 authenticated 读写 - 后端走 service_role 绕过）
CREATE POLICY "Enable all for backend" ON users FOR ALL USING (true);
CREATE POLICY "Enable all for backend" ON resume_records FOR ALL USING (true);
CREATE POLICY "Enable all for backend" ON resume_versions FOR ALL USING (true);
CREATE POLICY "Enable all for backend" ON experience_answers FOR ALL USING (true);
CREATE POLICY "Enable all for backend" ON ats_reports FOR ALL USING (true);

-- ====================================================
-- 完成
-- ====================================================
SELECT 'Schema initialized successfully!' AS status;
