-- ====================================================
-- 简历星球 - 面试助手 Agent 数据库表
-- ====================================================

-- 1. 启用 pgvector 扩展
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. 面试会话表
CREATE TABLE IF NOT EXISTS interview_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    resume_id BIGINT NOT NULL REFERENCES resume_records (id) ON DELETE CASCADE,
    mode VARCHAR(30) NOT NULL CHECK (mode IN ('diagnose', 'technical', 'behavioral', 'simulation')),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
    current_question_index INT DEFAULT 0,
    total_questions INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_interview_sessions_user ON interview_sessions (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_interview_sessions_resume ON interview_sessions (resume_id);

-- 3. 面试消息表
CREATE TABLE IF NOT EXISTS interview_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES interview_sessions (session_id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant', 'tool')),
    content TEXT,
    tool_calls JSONB,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_interview_messages_session ON interview_messages (session_id, created_at);

-- 4. 面试报告表
CREATE TABLE IF NOT EXISTS interview_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES interview_sessions (session_id) ON DELETE CASCADE UNIQUE,
    overall_score NUMERIC(3,1),
    strengths JSONB DEFAULT '[]',
    weaknesses JSONB DEFAULT '[]',
    suggestions JSONB DEFAULT '[]',
    full_report TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_interview_reports_session ON interview_reports (session_id);

-- 5. 简历片段向量表
CREATE TABLE IF NOT EXISTS resume_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES interview_sessions (session_id) ON DELETE CASCADE,
    chunk_index INT NOT NULL,
    content TEXT NOT NULL,
    embedding VECTOR(1024)
);
CREATE INDEX IF NOT EXISTS idx_resume_chunks_session ON resume_chunks (session_id);
CREATE INDEX IF NOT EXISTS idx_resume_chunks_embedding ON resume_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- 6. 面试题库向量表
CREATE TABLE IF NOT EXISTS question_bank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    category VARCHAR(30) NOT NULL,
    role VARCHAR(50),
    difficulty VARCHAR(20),
    tags TEXT[] DEFAULT '{}',
    embedding VECTOR(1024)
);
CREATE INDEX IF NOT EXISTS idx_question_bank_embedding ON question_bank USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- ====================================================
-- 触发器：自动更新 interview_sessions.updated_at
-- ====================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_interview_sessions_updated_at') THEN
        CREATE TRIGGER update_interview_sessions_updated_at
            BEFORE UPDATE ON interview_sessions
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;

-- ====================================================
-- RLS 策略
-- ====================================================
ALTER TABLE interview_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE resume_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE question_bank ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for backend" ON interview_sessions FOR ALL USING (true);
CREATE POLICY "Enable all for backend" ON interview_messages FOR ALL USING (true);
CREATE POLICY "Enable all for backend" ON interview_reports FOR ALL USING (true);
CREATE POLICY "Enable all for backend" ON resume_chunks FOR ALL USING (true);
CREATE POLICY "Enable all for backend" ON question_bank FOR ALL USING (true);

-- ====================================================
-- RPC 函数：向量检索
-- ====================================================

-- 检索简历片段
CREATE OR REPLACE FUNCTION search_resume_chunks(
    query_session_id UUID,
    query_embedding TEXT,
    top_k INT DEFAULT 3
) RETURNS TABLE(content TEXT, chunk_index INT, similarity FLOAT) AS $$
BEGIN
    RETURN QUERY
    SELECT
        rc.content,
        rc.chunk_index,
        1 - (rc.embedding <=> query_embedding::VECTOR) AS similarity
    FROM resume_chunks rc
    WHERE rc.session_id = query_session_id
    ORDER BY rc.embedding <=> query_embedding::VECTOR
    LIMIT top_k;
END;
$$ LANGUAGE plpgsql;

-- 检索面试题库
CREATE OR REPLACE FUNCTION search_question_bank(
    query_embedding TEXT,
    top_k INT DEFAULT 5
) RETURNS TABLE(question TEXT, category VARCHAR, role VARCHAR, difficulty VARCHAR, tags TEXT[], similarity FLOAT) AS $$
BEGIN
    RETURN QUERY
    SELECT
        qb.question,
        qb.category,
        qb.role,
        qb.difficulty,
        qb.tags,
        1 - (qb.embedding <=> query_embedding::VECTOR) AS similarity
    FROM question_bank qb
    ORDER BY qb.embedding <=> query_embedding::VECTOR
    LIMIT top_k;
END;
$$ LANGUAGE plpgsql;
